import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { monserrat } from './ui/fonts'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'E-commerce Carlos Valencia',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${monserrat.className} antialiased`}>
        <h1>Pagina web</h1>
        {children}
      </body>
    </html>
  )
}
